"""add campo OrdemServico

Revision ID: 106e1b035887
Revises: 
Create Date: 2024-03-25 15:12:25.272925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '106e1b035887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('dataCadastro', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('usuario')
    op.drop_table('cliente')
    op.drop_table('OrdensDeServico')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrdensDeServico',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('servico', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('posto_servico', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('assinatura', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('observacao', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('responsavel', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('responsavel_type', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('dataCadastro', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('usuarios')
    op.drop_table('Clientes')
    # ### end Alembic commands ###
