"""alter_01_usuario

Revision ID: 99de56e1cbb7
Revises: b89b85cb60e8
Create Date: 2024-03-25 16:44:55.805642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99de56e1cbb7'
down_revision = 'b89b85cb60e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('login')

    # ### end Alembic commands ###
