"""alter_03_OrdemServico

Revision ID: 9cc8c31e9abc
Revises: cdef51828dc1
Create Date: 2024-05-14 10:13:32.746921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cc8c31e9abc'
down_revision = 'cdef51828dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataRealizacao', sa.DateTime(), nullable=False))
        batch_op.drop_column('posto_servico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posto_servico', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('dataRealizacao')

    # ### end Alembic commands ###
