"""alter_01_OrdemServico

Revision ID: b89b85cb60e8
Revises: 106e1b035887
Create Date: 2024-03-25 15:44:33.838133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89b85cb60e8'
down_revision = '106e1b035887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responsavel_type', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('posto_servico', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('assinatura', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico')
    # ### end Alembic commands ###
