"""Adicionando novos campos e renomeando assinatura

Revision ID: d3893af3cd0e
Revises: 99de56e1cbb7
Create Date: 2024-05-02 15:29:09.433116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3893af3cd0e'
down_revision = '99de56e1cbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limpeza', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('poda_Plantas', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('poda_Grama', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('outros', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('outros_Descricao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura_Jardineiro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura_Responsavel', sa.String(length=255), nullable=True))
        batch_op.drop_column('descricao')
        batch_op.drop_column('assinatura')
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('descricao', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('assinatura_Responsavel')
        batch_op.drop_column('assinatura_Jardineiro')
        batch_op.drop_column('outros_Descricao')
        batch_op.drop_column('outros')
        batch_op.drop_column('poda_Grama')
        batch_op.drop_column('poda_Plantas')
        batch_op.drop_column('limpeza')

    # ### end Alembic commands ###
